name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Instala los módulos que necesitas
      - name: Install modules
        shell: pwsh   # <-- usa el pwsh del runner
        run: |
          Install-Module PSScriptAnalyzer,Pester -Force -Scope CurrentUser

      - name: Lint
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path scripts/dark.ps1 -Recurse -Severity Warning

      - name: Tests
        shell: pwsh
        run: Invoke-Pester -Path tests -Passthru
