name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          pwsh-version: '7.x'
      - name: Install modules
        run: Install-Module PSScriptAnalyzer,Pester -Force -Scope CurrentUser
      - name: Lint
        run: Invoke-ScriptAnalyzer -Path scripts/dark.ps1 -Recurse -Severity Warning
      - name: Test
        run: Invoke-Pester -Path tests -Passthru
